# Generated by Django 6.0.2 on 2026-03-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="Todo",
            name="content",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
